#!/bin/sh
# setup_subnet_route.sh
#
# Creates/updates an rc.d wrapper that runs "tailscale up" at boot with
# your chosen settings (subnet routing or Tailscale-only mode).
#
# Usage examples:
#   sh setup_subnet_route.sh --mode tailscale-only
#   sh setup_subnet_route.sh --mode subnet --subnet 192.168.29.0/24
#   sh setup_subnet_route.sh --mode subnet --subnet 192.168.29.0/24 --authkey tskey-auth-XXXX

set -eu

MODE=""
SUBNET=""
AUTHKEY=""
ACCEPT_DNS="false"

while [ $# -gt 0 ]; do
  case "$1" in
    --mode)
      MODE="$2"; shift 2;;
    --subnet)
      SUBNET="$2"; shift 2;;
    --authkey)
      AUTHKEY="$2"; shift 2;;
    --accept-dns)
      ACCEPT_DNS="$2"; shift 2;;
    *)
      echo "Unknown arg: $1" >&2; exit 1;;
  esac
done

if [ -z "$MODE" ]; then
  echo "ERROR: --mode tailscale-only | subnet required." >&2
  exit 1
fi

TS_BIN="/usr/local/bin/tailscale"
RC_SCRIPT="/usr/local/etc/rc.d/tailscale-route"

if [ ! -x "$TS_BIN" ]; then
  echo "ERROR: Tailscale not installed? Missing $TS_BIN" >&2
  exit 1
fi

TS_CMD="$TS_BIN up --accept-dns=$ACCEPT_DNS"

if [ -n "$AUTHKEY" ]; then
  TS_CMD="$TS_CMD --authkey $AUTHKEY"
fi

case "$MODE" in
  tailscale-only)
    echo "=== Configuring Tailscale-only mode (no subnet routing)."
    ;;
  subnet)
    if [ -z "$SUBNET" ]; then
      echo "ERROR: --subnet required in subnet mode." >&2
      exit 1
    fi
    echo "=== Configuring subnet routing for: $SUBNET"
    TS_CMD="$TS_CMD --advertise-routes=$SUBNET"
    ;;
  *)
    echo "ERROR: Invalid mode: $MODE (use tailscale-only or subnet)." >&2
    exit 1;;
esac

echo "=== Writing rc.d helper: $RC_SCRIPT"
cat > "$RC_SCRIPT" <<EOF
#!/bin/sh
#
# Auto Tailscale up helper
# Generated by setup_subnet_route.sh on $(date)
#
# PROVIDE: tailscale_route
# REQUIRE: LOGIN tailscaled
# KEYWORD: shutdown

. /etc/rc.subr

name="tailscale_route"
rcvar="tailscale_route_enable"
start_cmd="tailscale_route_start"
stop_cmd=":"

tailscale_route_start()
{
    sleep 5
    $TS_CMD
}

load_rc_config \$name
run_rc_command "\$1"
EOF

chmod +x "$RC_SCRIPT"
sysrc -f /etc/rc.conf tailscale_route_enable=YES

echo
echo ">>> setup_subnet_route.sh complete."
echo ">>> Start it now: service tailscale-route start"
echo
if [ "$MODE" = "subnet" ]; then
  echo ">>> IMPORTANT: After starting, approve route in Tailscale admin -> Routes."
fi
echo